# Generated by Django 5.0.6 on 2024-07-03 15:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked')], default='available', max_length=12, verbose_name='Status')),
                ('bike_model', models.CharField(max_length=140, verbose_name='Bike model')),
            ],
            options={
                'verbose_name': 'Bike',
                'verbose_name_plural': 'Bikes',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status'], name='bike_bike_status_48400f_idx'), models.Index(fields=['bike_model'], name='bike_bike_bike_mo_3c851f_idx')],
            },
        ),
    ]
