# Generated by Django 5.0.6 on 2024-07-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='rent_price',
            field=models.FloatField(default=0, verbose_name='Rent price'),
        ),
    ]
