# Generated by Django 5.0.6 on 2024-07-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_bike_rent_price'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bike',
            name='bike_bike_status_48400f_idx',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='status',
        ),
    ]
