# Generated by Django 5.0.6 on 2024-07-03 15:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bike', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('status', models.CharField(choices=[('created', 'Created'), ('confirmed', 'Confirmed'), ('current', 'Current'), ('canceled', 'Canceled'), ('finished', 'Finished')], default='created', max_length=12, verbose_name='Status')),
                ('rent_price', models.FloatField(default=0, verbose_name='Rent price')),
                ('start_at', models.DateTimeField(verbose_name='Start time')),
                ('finish_at', models.DateTimeField(verbose_name='End time')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='bike.bike', verbose_name='Bike')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Rent',
                'verbose_name_plural': 'Rents',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['start_at', 'finish_at'], name='rent_rent_start_a_cc06f1_idx')],
                'unique_together': {('user', 'bike')},
            },
        ),
    ]
