# Generated by Django 5.0.6 on 2024-07-04 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='rent_price',
        ),
    ]
