# Generated by Django 5.0.6 on 2024-07-05 10:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_alter_rent_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('bike_num', models.IntegerField(default=0, verbose_name='Number of bikes')),
                ('booked_bike_num', models.IntegerField(default=0, verbose_name='Number of booked bikes')),
                ('available_bike_num', models.IntegerField(default=0, verbose_name='Number of available bikes')),
                ('total_rent', models.FloatField(default=0.0, verbose_name='Total rent')),
            ],
            options={
                'verbose_name': 'Stats',
                'verbose_name_plural': 'Stats',
                'ordering': ('-created_at',),
            },
        ),
    ]
