name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: Run Docker Compose
      run: docker-compose up -d --build

    - name: Run Tests
      run: docker exec -it backend poetry run pytest -v